## MySQL 数据库
spring:
  datasource:
    url: jdbc:mysql://hx.mysql.cn:3316/rule?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useAffectedRows=true
    username: root
    password: root,./159357
    driver-class-name: com.mysql.cj.jdbc.Driver

    # Redis连接信息
  redis:
    database: 5  # Redis数据库索引（默认为0）
    host: 192.168.56.1 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: redisAdmin123456
    timeout: 10000 # 连接超时时间（毫秒）
    lettuce:
      pool:  #################redis线程池设置#################
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 500 # 连接池中的最大空闲连接
        min-idle: 50  # 连接池中的最小空闲连接

# 日志文件
logging:
  config: classpath:logback-winner.xml

# mybatis 配置
mybatis:
  type-aliases-package: hx.com.example.rule.dto # 实体映射基础包
  config-location: classpath:/mybatis/mybatis-config.xml   # mybatis 配置文件
  mapper-locations: classpath:/mapper/*.xml # mapper文件
  mapper-sql-locations: classpath:/mappersql/*.mapper

mapper:
  mappers: hx.data.mybatis.mapper.BaseMapper,tk.mybatis.mapper.common.Mapper   # mappers 多个接口时逗号隔开，ps:MySqlMapper不能配置 tk.mybatis.mapper.common.Mapper
  basePackage: hx.com.example.rule.dao   # dao基础包
  not-empty: false
  identity: MYSQL

#spring.datasource.hikari.jdbc-url= jdbc:mysql://hx.mysql.cn:3316/rule?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useAffectedRows=true
#spring.datasource.hikari.username= root
#spring.datasource.hikari.password= root,./159357
#spring.datasource.hikari.driver-class-name=com.mysql.cj.jdbc.Driver

#################redis哨兵设置#################
# Redis服务器master的名字
#spring.redis.sentinel.master=master8026
# redis-sentinel的配置地址和端口
#spring.redis.sentinel.nodes=10.189.80.25:26379,10.189.80.26:26379,10.189.80.27:26378



#redis集群配置
#spring.redis.cluster.nodes=192.168.177.128:7001,192.168.177.128:7002,192.168.177.128:7003,192.168.177.128:7004,192.168.177.128:7005,192.168.177.128:7006
#spring.redis.cluster.max-redirects=3


## Dubbo 服务提供者配置
#spring.dubbo.application.name=consumer-provider
#spring.dubbo.registry.address=zookeeper://192.168.56.1:2183
#spring.dubbo.protocol.name=dubbo
#spring.dubbo.protocol.port=20880
#spring.dubbo.scan=hx.com.example.rule.impl
#spring.dubbo.application.registries.timeout=10000
#spring.dubbo.application.registries.session=100000


#spring.application.name=provider-consumerssss
##spring.dubbo.server=false
#spring.dubbo.registry=zookeeper://192.168.56.1:2183
#spring.dubbo.protocol=dubbo
#zookeeper.connection.url=192.168.56.1:2183
#zookeeper.lockPath.prefix=rule







